export const GET_ERRORS = "GET_ERRORS";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const ADMIN_ADD = "ADMIN_ADD";
export const ADMIN_UPDATE = "ADMIN_UPDATE";
export const LOGOUT = "LOGOUT";

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
///////////////////////////Vocabualary///////////////////////////
export const GET_VOCABULARY = "GET_VOCABULARY";
export const VOCABULARY_ADD = "VOCABULARY_ADD";
export const VOCABULARY_UPDATE = "VOCABULARY_UPDATE";
export const VOCABULARY_DELETE = "VOCABULARY_DELETE";

export const GET_INTR_VOCABULARY = "GET_VOCABULARY";
export const INTR_VOCABULARY_ADD = "INTR_VOCABULARY_ADD";
export const INTR_VOCABULARY_UPDATE = "INTR_VOCABULARY_UPDATE";
export const INTR_VOCABULARY_DELETE = "INTR_VOCABULARY_DELETE";

export const GET_ADV_VOCABULARY = "GET_VOCABULARY";
export const ADV_VOCABULARY_ADD = "ADV_VOCABULARY_ADD";
export const ADV_VOCABULARY_UPDATE = "ADV_VOCABULARY_UPDATE";
export const ADV_VOCABULARY_DELETE = "ADV_VOCABULARY_DELETE";

/////////////////////Grammar/////////////////////////////////////
export const GET_GRAMMAR = "GET_GRAMMAR";
export const GRAMMAR_ADD = "GRAMMAR_ADD";
export const GRAMMAR_UPDATE = "GRAMMAR_UPDATE";
export const GRAMMAR_DELETE = "GRAMMAR_DELETE";

export const GET_INTR_GRAMMAR = "GET_INTR_GRAMMAR";
export const INTR_GRAMMAR_ADD = "INTR_GRAMMAR_ADD";
export const INTR_GRAMMAR_UPDATE = "INTR_GRAMMAR_UPDATE";
export const INTR_GRAMMAR_DELETE = "INTR_GRAMMAR_DELETE";

export const GET_ADV_GRAMMAR = "GET_ADV__GRAMMAR";
export const ADV_GRAMMAR_ADD = "ADV_GRAMMAR_ADD";
export const ADV_GRAMMAR_UPDATE = "ADV_GRAMMAR_UPDATE";
export const ADV_GRAMMAR_DELETE = "ADV_GRAMMAR_DELETE";

////////////////////Tutorial Vedio///////////////////////////////
export const GET_TUTORIAL_VEDIO = "GET_TUTORIAL_VEDIO";
export const TUTORIAL_VEDIO_ADD = "TUTORIAL_VEDIO_ADD";
export const TUTORIAL_VEDIO_DELETE = "TUTORIAL_VEDIO_DELETE";
export const TUTORIAL_VEDIO_UPDATE = "TUTORIAL_VEDIO_UPDATE";

export const GET_INTR_TUTORIAL_VEDIO = "GET_INTR_TUTORIAL_VEDIO";
export const INTR_TUTORIAL_VEDIO_ADD = "TUTORIAL_VEDIO_ADD";
export const INTR_TUTORIAL_VEDIO_DELETE = "TUTORIAL_VEDIO_DELETE";
export const INTR_TUTORIAL_VEDIO_UPDATE = "TUTORIAL_VEDIO_UPDATE";

export const TUTORIAL_ADV_VEDIO_ADD = "TUTORIAL_ADV_VEDIO_ADD";
export const ADV_TUTORIAL_VEDIO_DELETE = "ADV_TUTORIAL_VEDIO_DELETE";
export const ADV_TUTORIAL_VEDIO_UPDATE = "ADV_TUTORIAL_VEDIO_UPDATE";
export const ADV_GET_TUTORIAL_VEDIO = "ADV_GET_TUTORIAL_VEDIO";

//////////////////////////////Exercise////////////////////////////////
export const GET_EXERCISE = "GET_EXERCISE";
export const EXERCISE_ADD = "EXERCISE_ADD";
export const EXERCISE_UPDATE = "EXERCISE_UPDATE";
export const EXERCISE_DELETE = "EXERCISE_DELETE";

export const GET_INTR_EXERCISE = "GET_INTR_EXERCISE";
export const INTR_EXERCISE_ADD = "INTR_EXERCISE_ADD";
export const INTR_EXERCISE_UPDATE = "INTR_EXERCISE_UPDATE";
export const INTR_EXERCISE_DELETE = "INTR_EXERCISE_DELETE";

export const GET_ADV_EXERCISE = "GET_ADV_EXERCISE";
export const ADV_EXERCISE_ADD = "ADV_EXERCISE_ADD";
export const ADV_EXERCISE_UPDATE = "ADV_EXERCISE_UPDATE";
export const ADV_EXERCISE_DELETE = "ADV_EXERCISE_DELETE";
